### ISSUE TITLE
diffDeep not handle RawConfig

### ISSUE THREAD

**Issue by zyf0330** [node-config/node-config#478]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [x] bug report
  - [  ]  feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:
If there is a RawConfig type prop value, and `diffDeep(it, it)`, there is a diff of `{}`
### What is the expected behavior?
It should be nothing
### Please tell us about your environment:

 -  node-config version: x.x.x
 -  node-version: x.x.x
 
### Other information

(e.g. are you using an environment besides Node.js?)

**Comment by markstos** [comment]
Closing as stale.
