### ISSUE TITLE
When project node environments include hostname, config return is not correct

### ISSUE THREAD

**Issue by MedusaLeee** [node-config/node-config#509]
### Node and Config version:
-  node-config version: 2.0.1
-  node-version: 10.10.0

### Problem

I find a problem when environments include hostname, node-config can not return a correct config field.

I find the reason:

for example:

Environments config files: development.json production.json  test.json

Current environment: development

Current hostname: test

The final config = test.json extend development.json extend default.json

but I think final config = development.json extend default.json

because test.json is node environment config not host config, so I think current hostname config should have specific suffix。e.g. test-host.json

**Comment by markstos** [comment]
Closing as stale.
