### ISSUE TITLE
node-config is not working with tsconfig-paths

### ISSUE THREAD

**Issue by sandangel** [node-config/node-config#519]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

~~We'd like to migrate our project to typescript. Our approach is registering ts-node in a .js file, then require to other typescript files. So all the path work the same with before. The problem is in our application, we are using `config` and it does not work with the above approach.~~

Currently if I register ts-node and tsconfig-paths together with ‘config’, there will be an error.

Here is the step to reproduce
```javascript
// test.js
'use strict';

const path = require('path');

const tsconfigPath = path.join(__dirname, './tsconfig.json');
const tsconfig = require(tsconfigPath);

// Register TS compilation.
require('ts-node').register({
  project: tsconfigPath,
});

require('tsconfig-paths').register({
  baseUrl: path.dirname(tsconfigPath),
  paths: tsconfig.compilerOptions.paths,
});

require('./test-config');
```

```typescript
// test-config.ts
import { get } from 'config';

const id = get('some_env_id');
console.log(id);
```

```sh
TypeError: config_1.get is not a function
    at Object.<anonymous> (/Users/sand/Works/zehitomo/zehitomo-worker/test-config.ts:3:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.m._compile (/Users/sand/Works/zehitomo/zehitomo-worker/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/sand/Works/zehitomo/zehitomo-worker/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

I tried with default import

```typescript
import config from 'config'

const id = config.get('some_env_id');
// the same
```

```sh
const id = config.get('some_env_id');
                  ^
TypeError: config_1.default.get is not a function
```

and with `require` as well
```typescript
const config = require('config');
```
```sh
TypeError: config.get is not a function
```

Here is my tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "allowJs": false,
    "checkJs": false,
    "skipLibCheck": true,
    "outDir": "./",
    "rootDir": "./",
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "paths": {},
    "typeRoots": ["./node_modules/@types"],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "sourceMap": true
  },
  "include": ["./**/*.ts"],
  "exclude": ["node_modules"]
}
```

### What is the expected behavior?
~~It should work the same when import in javascript file and typescript file~~
it should work when I use tsconfig-paths.

### Please tell us about your environment:

 -  node-config version: 2.0.1
 -  node-version: 10.14.1
 
### Other information

(e.g. are you using an environment besides Node.js?)

**Comment by lorenwest** [comment]
Closing as duplicates of various [typescript discussions](https://github.com/lorenwest/node-config/issues?utf8=%E2%9C%93&q=is%3Aissue+typescript+) and enhancements.

If there's additional functionality you're looking for after reading those discussions, feel free to re-open the issue with details. I'm not a huge fan of typescript, but there are some contributors that could help out.

**Comment by sandangel** [comment]
hi @lorenwest , thanks for your response. I have discovered that the error happen only when I register tsconfig-paths, which is not related to other typescript issues that have been discussed. Coukd I reopen this issue?

**Comment by markstos** [comment]
Closing as stale-- no interest in 5 years.
