### ISSUE TITLE
on Debian 8 & 9 I faced with strange issue: the production.yaml is not loaded

### ISSUE THREAD

**Issue by thanhlq** [node-config/node-config#523]
-  node-config version: 3.0.1
 -  node-version: 8.14.1
 - OS: Debian 8 & 9
 
I use two file: development.yaml & production.yaml for diff definitions in each env.

Today I faced with the problem that the production.yaml is not loaded on the Debian with NODE_ENV already defined as production -> instead of that, it loaded the development.yaml file.

If I remove development.yaml then production.yaml is loaded. Strange to me!

**Comment by markstos** [comment]
Closing as stale.
