### ISSUE TITLE
NODE_APP_INSTANCE still erroring out despite following all Wiki steps...

### ISSUE THREAD

**Issue by marbuser** [node-config/node-config#526]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [ x ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

Following as the wiki instructed. Using pm2 to deploy my app, and was having some issues with NODE_APP_INSTANCE. Specifically this error;
`FATAL: NODE_APP_INSTANCE value of '0' did not match any instance config file names.`

I tried making a 0-default.json/js file with `{}`, no luck it still errored out. I tried setting the `instance_var` variable as recommended by a PM2 dev, no luck there either. Not really sure what else could be effecting this. I even set strict mode to off in my actual servers environment variables and it was still enabled upon running again. No clue what is going on here, but feels like a bug.

### What is the expected behavior?
If strict mode is set to off, it should actually turn off? If the files are created and present, they should be used? Not sure really what to put here other than just "the app should deploy without crashing" lol.

### Please tell us about your environment:

 -  node-config version: 3.0.1
 -  node-version: 11.5.0
 
### Other information

(e.g. are you using an environment besides Node.js?)
No

**Comment by markstos** [comment]
Closing as stale due lack of activity in the last 5 years.
