### ISSUE TITLE
More then one sub module uses setModelDefaults f

### ISSUE THREAD

**Issue by guylevin** [node-config/node-config#543]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [X] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

When using pattern described on this page
https://github.com/lorenwest/node-config/wiki/Sub-Module-Configuration
For multiple sub modules 

And using this inside sub-module to set default config
```config.util.setModuleDefaults(moduleName, defaultConfig)```
Without having those values on default.json

It fails in the second sub-module which tries to set it's defaults

This row, throws an exception because mergeInto is undefined
```var isDeferredFunc = mergeInto[prop] instanceof DeferredConfig;```

### Please tell us about your environment:

 -  node-config version: 3.0.1
 -  node-version: 10.8.0
 
### Other information

(e.g. are you using an environment besides Node.js?)

**Comment by markstos** [comment]
closing as stale.
