### ISSUE TITLE
Order of precedence mismatch between code and wiki

### ISSUE THREAD

**Issue by mtlewis** [node-config/node-config#584]
### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
* In version 3.2.4, the values in custom-env-variables.json override the NODE_CONFIG command line option (I believe it's [here](https://github.com/lorenwest/node-config/blob/master/lib/config.js#L644) in the source.
* In [the wiki](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables), NODE_CONFIG is described as the only way of overriding the values in custom-environment-variables.json.

### What is the expected behavior?
Not sure whether the wiki or code reflects the intended behavior, but one should be updated to match the other. :)

**Comment by markstos** [comment]
I made the backwards compatible change to update the wiki to match the code. I added this to the NODE_CONFIG section:

_Note that "custom environment variables" described above overrride this._

Thanks for the report. Closing.
