### ISSUE TITLE
Feature Request: `NODE_CONFIG_FILE` environment variable for config injection via file

### ISSUE THREAD

**Issue by akloeber** [node-config/node-config#605]
### I'm submitting a ... 
  - [  ] bug report
  - [x] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the expected behavior?
In addition to environment variable `NODE_CONFIG` that allows injection of an inline object literal, an analogue `NODE_CONFIG_FILE` environment variable  should support injection via a path to a file that contains a configuration object.

__Background:__
I'm deploying a Node.js application as a docker container and the suggested way for passing secret values like passwords, keys, etc. to the container is via _docker secrets_ (see https://docs.docker.com/engine/swarm/secrets/). Unfortunately docker only supports exposure of a secret as a file and not as an environment variable (according to https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images, this was an intentional decision for security reasons).
With support for `NODE_CONFIG_FILE` in place it would be simple to provide secret config values via Docker secrets to the container.

Right now I'm using the following code to achieve this:
```typescript
function loadNodeConfigFile() {
  if (process.env.NODE_CONFIG_FILE) {
    const configObj = (config.util as typeof config.util & {
      parseFile(path: string): any;
    }).parseFile(resolve(process.env.NODE_CONFIG_FILE));
    if (configObj) {
      config.util.extendDeep(config, configObj);
    }
  }
}
```

I could create a PR if you also consider this a useful addition to `node-config`.

**Comment by synapdk** [comment]
I haven't used Docker secrets but I'm interested in this. The [introductory blog post](https://www.docker.com/blog/docker-secrets-management/) says it uses an in-memory filesystem, so I wonder if you could use `NODE_CONFIG_DIR` to append something like `/run/secrets/config` as a directory and parse any secret files in there?

**Comment by lorenwest** [comment]
Could you symlink the secrets file into a file under your /config directory?

**Comment by akloeber** [comment]
@synapdk Sure you can but then you need to provide the entire application configuration via Docker secrets. I think in most cases this is not what we want. Default and environment-specific configuration should be built into the image and pointed to via `NODE_CONFIG_DIR` and only sensitive data like passwords, API keys, etc. are provided via Docker secrets.

**Comment by akloeber** [comment]
@lorenwest This only works when the symlink is created at container start-time before the node process is started and thus makes the container entrypoint more complex.

**Comment by synapdk** [comment]
[The documentation](https://github.com/lorenwest/node-config/wiki/Configuration-Files#config-directory) indicates that you can have multiple directories separated by a delimiter, so I was hoping you could use both and have just the secret values in `/run/secrets`.

**Comment by akloeber** [comment]
@synapdk You are right I didn't know about the possibility to list multiple directories. Given that `node-config` ignores other secrets that are potentially mounted at `/run/secrets`(like SSH-keys) that would be a workaround.
 
I don't think that it is possible to expand an entire directory as a secret under `/run/secrets/config` or a file at a deep path like `/run/secrets/config/local.yml` to avoid conflicts.

**Comment by lorenwest** [comment]
Adding an entrypoint environment variable vs. symlink is similar complexity and it's a domain specific solution to a domain specific problem.

We have to be sure we've exhausted alternatives before adding configuration to the configuration system.

**Comment by akloeber** [comment]
@lorenwest I agree that complexity is similar. Another downside of the symlink-approach is that the run-user then needs to have write privileges on the `NODE_CONFIG_DIR` directory which is suboptimal from a security perspective.

Of course, this problem here resides in the Docker-domain and can be resolved/worked around there, but it also appears in other domains:
- variables in Gitlab CI (https://docs.gitlab.com/ee/ci/variables/#custom-environment-variables-of-type-file)
- secrets in Kubernetes (https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod)

**Comment by lorenwest** [comment]
Wouldn't it be simpler to read the secrets file directly, and manage them in the code module that manages secrets?

It seems like secrets deserve extra security attention that a generic, globally available config structure doesn't provide.

**Comment by akloeber** [comment]
@lorenwest Yes, it's simple but you still have to implement that module for config management of secrets yourself. In the end you have 2 different mechanisms for accessing config values that have either different APIs or you have to re-implement `node-config`'s API in your own one. I also think that it is uncommon so separate sensitive config values / secrets from the non-sensitive ones _inside_ the application but that is a design decision.

Furthermore this issue does not only apply to secrets only. Variables in Gitlab CI exposed as files can be used for any kind of configuration. Also Docker has a mechanism for managing non-sensitive config values via `docker config` (https://docs.docker.com/engine/reference/commandline/config/) which I do not use but having `NODE_CONFIG_FILE` as suggested here would simplify usage of docker-managed configs as well.

**Comment by lorenwest** [comment]
From an enterprise perspective, storing secrets in global configs is the way they unwittingly leak into searchable deploy logs. The company I work with would consider that practice a security breach, and prioritized above other customer features for resolution.

My thought is this is feature creep. It clearly can be done without changing node-config, so it's not a critical feature. I will leave this issue open for others to chime into, and possibly offer a solution, tests, and documentation.

**Comment by akloeber** [comment]
@lorenwest This is getting off-topic - I didn't want to dive into a discussion about "enterprise"-worthy security. That's why I mentioned an analogue use case with `docker config`.

**Comment by hgrubst** [comment]
I would also like an off the shelf solution for this. But for now I use a docker entrypoint file that is responsible for loading the secret files as environment variables and providing the config as expected.
For those interested here the script that does the job : 
```
entrypoint.sh : 

#!/bin/sh

# Lookup all env var in the form XXX__FILE__ and if their value matches an existing file
# export the value of that file in an env var XXX
# Especially useful for docker secrets feature.
# For example you can define an env var DB_PASSWORD__FILE__=/var/run/secrets/db-password and the content of that secret file will be exported
# in env var DB_PASSWORD
for i in `env | grep __FILE__ | cut -d= -f 1`; do
 VAR=${i%__FILE__}
 eval "SECRET_FILE=\$${i}"
 if [ -f $SECRET_FILE ]; then
    FILE_CONTENT=`cat ${SECRET_FILE}`
    export $VAR="$FILE_CONTENT"
 else 
    echo "No such file $SECRET_FILE from env var $i"
 fi
done;

exec "$@"


```

**Comment by jdmarshall** [comment]
I have code that merges in some data from Consul or other places, and rather than trying to trick node-config into doing anything useful with it, we wrap node-config and use it as defaults, with other more volatile settings layered over the top, and a little lodash for the glue code.

**Comment by markstos** [comment]
Closing. The recommended solutions are described above.
