### ISSUE TITLE
load config file based on custom env param

### ISSUE THREAD

**Issue by Boredude** [node-config/node-config#626]
### I'm submitting a ... 
  - [  ] bug report
  - [x] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
config can be loaded only using NODE_ENV param

### What is the expected behavior?
ability to load config based on a custom env param

### Please tell us about your environment:

 -  node-config version: 3.3.1
 -  node-version: 10
 
### Other information

I'm using firebase functions and use two firebase projects for dev and production.
Firebase doesn't allow to override the NODE_ENV and it is always set to `production` 
If you would somehow be able to tell `config` to load the right config file based on your on custom enviornment variable that would be amazing!

**Comment by airdrummingfool** [comment]
You can use `NODE_CONFIG_ENV` instead of `NODE_ENV`. [From the wiki](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_env):

```
process.env.NODE_CONFIG_ENV = "qa";
process.env.NODE_ENV = "production";
var config = require('config');
console.log('NODE_CONFIG_ENV: ' + config.util.getEnv('NODE_CONFIG_ENV'));
```
The qa configuration will be used in place of production.

**Comment by Kenhuey** [comment]
> You can use `NODE_CONFIG_ENV` instead of `NODE_ENV`. [From the wiki](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_env):
> 
> ```
> process.env.NODE_CONFIG_ENV = "qa";
> process.env.NODE_ENV = "production";
> var config = require('config');
> console.log('NODE_CONFIG_ENV: ' + config.util.getEnv('NODE_CONFIG_ENV'));
> ```
> 
> The qa configuration will be used in place of production.

Not works :( NODE-CONFIG_ENV still development.

**Comment by miguelfbrito** [comment]
This might be related to how the `process.env` is being handled and not `node-config` itself.
You might need to invalidate the module cache to get the most recent `process.env`. 

For instance, I was facing this issue with `jest`. Reseting the modules cache (`jest.resetModules()`) before applying the `process.env.NODE_CONFIG_ENV = 'foobar'` solved it for me.

**Comment by markstos** [comment]
@Kenhuey Typo? Here you wrote "NODE-CONFIG_ENV" not "NODE_CONFIG_ENV"

**Comment by Kenhuey** [comment]
> @Kenhuey Typo? Here you wrote "NODE-CONFIG_ENV" not "NODE_CONFIG_ENV"

Sorry, it just my IME typo due reply. I use "NODE_CONFIG_ENV " in code.

**Comment by markstos** [comment]
I'm closing this because `NODE_CONFIG_ENV` exists. If there's really a bug, open a pull request with a failing test to demonstrate it. Otherwise, I'll assume there was an environmental issue here.
