### ISSUE TITLE
Dynamic requires break webpack bundling

### ISSUE THREAD

**Issue by gustavohenke** [node-config/node-config#635]
### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request or question

### What is the current behavior?
Using node-config with config files that require additional dependencies doesn't work when in a [Next.js project with `target: 'serverless'`](https://nextjs.org/docs/api-reference/next.config.js/build-target).

The `serverless` target bundles each route file independently with Webpack, so it has no external requires _by default_, even in the Node.js environment.

The following message appears when running the project:
> No YAML parser loaded.  Suggest adding js-yaml dependency to your package.json file.

And the following when building:

> ./node_modules/config/parser.js
> Critical dependency: the request of a dependency is an expression

...which means that because webpack couldn't analyse the config code, it didn't bundle js-yaml.

### What is the expected behavior?
Instead of using dynamic `require(DEP_NAME)`s, like here:

https://github.com/lorenwest/node-config/blob/ff64ba79e17adf6d0c49acacfa64c9c909378809/parser.js#L122

I suggest changing that to a function which has the require written plainly, like this:

```js
const requireYaml = () => require('js-yaml');
Yaml = requireJsYaml();
```

This should be enough to
1. make webpack bundling work again; and
2. avoid running unwanted code by still having conditional requires.

_* I'd be happy to submit a PR for this, if you like my suggestion._

### Please tell us about your environment:

 - node-config version: 3.3.3
 - node-version: 12.16.1
 - webpack: 4.44.1
 - next: 10.0.4

### More information
There are some ways around this, e.g. one can simply use the suggestions in the ["Webpack Usage" wiki](https://github.com/lorenwest/node-config/wiki/Webpack-Usage).
However, Next.js docs advises to [customise webpack configs only as a last resort](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config). Also, I'm using a framework because I don't like fiddling with build tools 😬 

Another suggestion is to replace requires to `config` with the following in my code:

```js
// Should be statically analysable
global.Yaml = require('js-yaml');
module.exports = require('config');
```

However, the `serverless` target is always the case when deploying to [Vercel](https://vercel.com), who heavily markets its product in the Next.js docs (and vice-versa).
So I guess that more users may have the same issue as me... I just couldn't find any meaningful resource before, so here I am debugging and reporting this issue.

**Comment by markstos** [comment]
The first suggestion seems OK. The loading is still dynamic, but fixes webpack. PR welcome.

**Comment by gustavohenke** [comment]
Hmm, actually, looks like #465 modified the code to what it is today because of this: https://github.com/lorenwest/node-config/issues/345#issuecomment-244579306

So looks like the fix I want may actually break someone's workflow...

I'm now wondering if it should be a rollup improvement to not break the build when finding a dependency that is not installed, like Webpack is doing?
WDYT?

**Comment by icarus-sullivan** [comment]
I know this is an old post, but I made a webpack plugin to help support this. You can get it on npm [node-config-webpack](https://www.npmjs.com/package/node-config-webpack). 

If your webpack configuration is also using `webpack-node-externals` (which most times it will be) you will need to add `config` to the allowlist. 

_Example_:
```javascript
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');
const NodeConfigWebpack = require('node-config-webpack');

process.env.NODE_ENV = slsw.lib.serverless.service.provider.environment.NODE_ENV;

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  externals: [nodeExternals({
    allowlist: ['config']
  })],
  plugins: [
    new NodeConfigWebpack(),
  ]
};
```

This plugin will automatically inject environment derived configuration with a limited set of functions (get, has).

**Comment by paulsmithkc** [comment]
@icarus-sullivan That looks like an interesting solution. But I'm immediately wary of the fact that it doesn't have a linked repo and issue list.

**Comment by markstos** [comment]
@paulsmithkc There's no guarantee that what you seen a linked repo matches what's been uploaded to NPM. If you are concerned the source is unsafe, you should unpack the source code downloaded from NPM and inspect it.

**Comment by markstos** [comment]
I'm closing this because `node-config-webpack` seems like a good solution.
