### ISSUE TITLE
Typescript 4.4.2 transpilation problem

### ISSUE THREAD

**Issue by pluschnikow** [node-config/node-config#657]
### I'm submitting a ... 
  - [X] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?

Example code:

When I import the get method in typescript...:
```
import { get } from 'config'

const config = get('my.config.path');
```

...and transpile the code with typescript 4.3.5v, it results into following js-code:

```
const config_1 = require("config");

const config = config_1.get('my.config.path');

```

Transpilation with typescript 4.4.2 results in following js-code:
```
const config_1 = require("config");

const config = (0, config_1.get)('my.config.path');

```

The transpiled code from 4.4.2 is not able to find the configuration.
All other packages are able to handle the new typescript transpilation result.

I tried to debug the config package a little bit and it seems to be a problem that the extended `this` scope gets lost and is not available in the `get` method anymore.

### Please tell us about your environment:

 -  node-config version: 3.3.6
 -  node-version: 14.17.5
 -  typescript version: 4.3.5 AND 4.4.2

**Comment by Weibye** [comment]
I have the exact same issue, unable to find my configs.

### Please tell us about your environment:
* node-config version: 3.3.1
* node-version: 16.6.2
* typescript version: 4.2.3

**Comment by markstos** [comment]
If TypeScript quit being able to transpile valid JavaScript, why don't you file a bug with TypeScript instead?

**Comment by davojan** [comment]
@markstos I think the typescript transpilation is totally correct here, I'll try to explain...

When we write `import { get } from 'config'` - we are importing the function `get` itself as a function. If the library supports such import, then it should export `get` function already bound to the right `config` object. So the typescript just become more strict here. I'm not sure but I guess there is no such spec that such es6 import must call function in the context of exported object (module.exports).

So, the workaround for us (typescript user) is to use `import config from 'config'` instead. But I think this is totally 'node-config' library's bug.

**Comment by markstos** [comment]
Hmm, When calling `config.get()`, it's important that `get`  `get` binds `this` to the calling method of `config`.  With 

```
import { get } from 'config'
```

Then nothing is bound to the `this` when calling `get`, right?

Then it's correct to `import config from 'config'` and call  `config.get()` after that. 

Could this be solved on the `node-config` side by expliciting binding doing something like `get.bind(config)` before export?

Feel free to experiment and see if you can get something like that to work.

**Comment by markstos** [comment]
I want to comment on this code pattern:

```
const config = get('my.config.path');
```

Here I presume that `config` is being set an object.  So you are following up with code like this:

```
if (config.boo) { ... }
if (config.zoo) { ... }
```

This pattern is less safe than more explicitly requesting each value, like: 

```
const boo = get('my.config.path.boo');
const zoo = get('my.config.path.zoo');
```
There is no protection against accidentally introducing a typo in the key name if call `config.oops` instead of a correct name. When if you typo a key passed to get:

```
const boo = get('my.config.path.oops');
```

... then `node-config` helpfully will throw an error to highlight the mistake

**Comment by davojan** [comment]
> Then nothing is bound to the `this` when calling `get`, right?
> Then it's correct to `import config from 'config'` and call `config.get()` after that.
Yes, absolutely.

> Could this be solved on the `node-config` side by expliciting binding doing something like `get.bind(config)` before export?

I think the fix should look like this: https://github.com/lorenwest/node-config/compare/master...davojan:patch-1
But I haven't tried it myself.

**Comment by markstos** [comment]
@davojan If you call bare `get` and `has`, what clue the code reader that these functions are related to configuration? Lodash has a method named `get`. You could rename during import as `configGet` and `configHas`, but if you are doing that clarity, why not just use `config.get` and `config.has`?

**Comment by davojan** [comment]
Yes, I totally agree, that using `config.get` leads to more understandable code, and I've already rewritten my code that way.

But I still think that there is a problem in exports design in this library. In modern js, if your intent is to export an instance of a class, than you probably should use `export default`, or in case of commonjs - `module.exports = { config: config }`. Nobody will guess by default that members of module's exports can't be used independently, that just doesn't make sense. And you are not in control how the library users are going to import it. And the evidence is that from many libraries I use only node-config has been broken after upgrade to typescript 4.4.

While changing module exports is a breaking major change I think that the best way to fix that design mistake is to export bound versions of the config object's methods. I think it'll definitely improve the library's quality.

**Comment by markstos** [comment]
@davojan I don't think it will hurt anything to explicitly bind `get` to `config`. Feel free to submit a PR and make sure tests pass.

**Comment by markstos** [comment]
Closing. The module wasn't being imported correctly.
