### ISSUE TITLE
Add support for `jsonc` file extension

### ISSUE THREAD

**Issue by erfanium** [node-config/node-config#671]
### I'm submitting a ... 
  - [  ] bug report
  - [ x ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
There's no support for jsonc (json with comment) file extention

### What is the expected behavior?
Add support for `jsonc` file extension

**Comment by lorenwest** [comment]
This functionality already exists in node-config, it's kind of buried in the wiki under the [File Formats](https://github.com/node-config/node-config/wiki/Configuration-Files#file-formats) section.

If that will suffice, you're set!

If there are other benefits to your favorite ```.jsonc``` library and you'd like to be a node-config contributor, feel free to discuss the rationale on this thread, then issue a pull request with this addition.

**Comment by erfanium** [comment]
Yeah, the functionality is already exists, but the package does not resolves `*.jsonc` files. Also there's no need to add a new parser for jsonc. we only need to resolve and consider `jsonc` files as `json`

**Comment by markstos** [comment]
Since we already supports JSON-with-comments because we support JSON5, A PR which adds support for the `.jsonc` extension would be accepted.

**Comment by ducaale** [comment]
Given that deno supports `.jsonc` for its configuration file, it would be convenient if node-config supported `.jsonc` extension as well.

**Comment by markstos** [comment]
I don't see how the Deno comment is relevant. node-config does not parse the Deno config file, Deno does.

Closing because we already have two file extensions that support the JSONC format, `.json` and `.json5`. 

Ref: https://deno.land/manual@v1.36.0/getting_started/configuration_file
