### ISSUE TITLE
Sops support

### ISSUE THREAD

**Issue by jr0dd** [node-config/node-config#672]
First off I wanted to give thanks for this. Being able to have one codebase for staging, testing and production is making my life so much easier.

I was curious what you all thought about the possibility of adding support for Mozilla SOPS to decrypt config files. Honestly, not sure how feasible it would even be since it is written in go. I'm still fairly new to node, but sops has been indispensable managing secrets for GitOps/DevOps.

**Comment by markstos** [comment]
This the first time anyone has mentioned [Mozilla SOPS](https://github.com/mozilla/sops) here. Given the lack of interest, it's unlikely there will be an attempt at native support.

I recommend looking at some way to integrate the two, like: 

  *  Have SOPS produce environment variables, which `node-config` rides.
  * Have SOPS produce any of the support file formats which `node-config` rides. Other code could possibly remove this file after has been read.
  * Using the JavaScript config file format, and calling SOPS through JavaScript.
  * Use the support for pluggable config file formats to write a plugin for the SOPS format: https://github.com/node-config/node-config/pull/557

I have not looked at SOPS at all to see what, if any options might be viable. k

**Comment by markstos** [comment]
I'm going to go ahead and close this since we aren't likely add support for many new config file formats at all since there's pluggable format support now, but you are welcome to continue to post about SOPS here in case some other interested user finds the post to discuss it.

**Comment by jr0dd** [comment]
> This the first time anyone has mentioned [Mozilla SOPS](https://github.com/mozilla/sops) here. Given the lack of interest, it's unlikely there will be an attempt at native support.
> 
> 
> 
> I recommend looking at some way to integrate the two, like: 
> 
> 
> 
>   *  Have SOPS produce environment variables, which `node-config` rides.
> 
>   * Have SOPS produce any of the support file formats which `node-config` rides. Other code could possibly remove this file after has been read.
> 
>   * Using the JavaScript config file format, and calling SOPS through JavaScript.
> 
>   * Use the support for pluggable config file formats to write a plugin for the SOPS format: https://github.com/node-config/node-config/pull/557
> 
> 
> 
> I have not looked at SOPS at all to see what, if any options might be viable. k

Yeah I kind of figured there wasn't much of an interest after searching around. 

Since I'm building containers the 2 methods I've considered are:

1. Storing the encrypted config files in my node app repo and having the encryption key stored as a GitHub secret. Then add decryption steps in the Dockerfile  so it's built in the ghcr image. 

2. Mounting the config files as kubernetes secrets for your lib to in-jest at runtime. 

Option 1 does allow for more CI to be ran, but if somehow, someone was able to get ahold of the image they would also have all these api keys unencrypted. 
Option 2 definitely gives that added security of sensitive data only being stored in the cluster, while sacrificing some CI tests.
