### ISSUE TITLE
feat: additional `CONFIG_ENV` to allow full compatibility with Next.js server

### ISSUE THREAD

**Issue by b3nThomas** [node-config/node-config#679]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/node-config/node-config/wiki

### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### Description

Here's our problem:
- Next **always** sets `NODE_ENV` to be `production` or `development`.
- We want to be able to use `dev`, `staging`, `production`, `test`, etc configs at our leisure for our Next apps.
- We would therefore use `NODE_CONFIG_ENV` to override this and use the correct config. ([Docs](https://github.com/node-config/node-config/wiki/Environment-Variables#node_config_env))
- Next’s server does not allow the use of ANY environment variables that start with `NODE_`. ([Docs](https://nextjs.org/docs/messages/env-key-not-allowed) / [Src](https://github.com/vercel/next.js/blob/b62bb97b6fad58d340eac997995f3370dfbc2008/packages/next/build/webpack-config.ts#L2316))
- We therefore cannot use this lib as we'd like to, which makes us very sad as it's fantastic 😢 

This feature request is therefore fairly simple, would it be possible to add another environment variable for setting the config env, namely one that does not start with `NODE_`? This would then make this library fully compatible with the Next.js server (`next start`). Maybe `CONFIG_ENV` or `APP_CONFIG_ENV`?

I completely understand that you may not want the needs of another library/framework driving requirements in your library, however I can see more and more people running into this going forward and it would be amazing if this limitation could be overcome so that `next.js` and `node-config` can be married in holy matrimony ✨💍✨ 

Many thanks for your consideration 😄

**Comment by markstos** [comment]
I consider it a bug with Next.js that they they have reserved `NODE_` for their own internal use. `node-config` and other projects were using variables with this prefix long before Next.js existed. It would be different if we were using `__NEXTJS_` as our prefix, but this project has doing that's specific to Next.js.

If Next.js insists on owning the `NODE_` environment variable name space, then I recommend a Next.js developer or user publish a wrapper Node module, like `nextjs-config`.  This module can set `NODE_CONFIG_ENV`,  require node-config, and unset `NODE_CONFIG_ENV`, all before `Next.js` notices that another project dared to set a variable using the `NODE_` prefix. 

You can follow the same pattern in your individual code without a wrapper module.
