### ISSUE TITLE
broken webpack bundling

### ISSUE THREAD

**Issue by paulsmithkc** [node-config/node-config#681]
### I'm submitting a ... 
  - [x] bug report

### What is the current behavior?

When bundling my app code with webpack I get **18** different warnings, due to the `config` package. 

There is one instance of this error:
```
WARNING in ./node_modules/config/parser.js 55:7-25
require.extensions is not supported by webpack. Use a loader instead.
 @ ./node_modules/config/lib/config.js 10:13-33
 @ ./index.js
```

And 17 instances of this error, with different line numbers:
```
WARNING in ./node_modules/config/parser.js
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/config/lib/config.js 10:13-33
 @ ./index.js
```

### Example Project

Below you can find the relevant code:

#### package.json
```json
{
  "scripts": {
    "start": "node index.js",
    "build": "webpack build"
  },
  "engines": {
    "npm": ">=8.0.0",
    "node": ">=16.0.0"
  },
  "dependencies": {
    "config": "^3.3.7"
  },
  "devDependencies": {
    "webpack": "^5.73.0",
    "webpack-cli": "^4.10.0"
  }
}
```

#### config/default.json
```json
{ "env": "development" }
```

#### custom-environment-variables.json
```json
{ "env": "NODE_ENV" }
```

#### index.js
```js
const config = require('config');
const env = config.get('env');
console.log(env);
```

#### webpack.config.js
```js
const path = require('path');

const config = {
  mode: 'production',
  entry: './index.js',
  target: 'node',
  output: {
    path: path.resolve('build'),
    filename: 'index.js',
    chunkFormat: 'commonjs',
  },
};

module.exports = config;
```

### What is the expected behavior?

Webpack generates **0** errors.

### Please tell us about your environment:

 -  node-config version: 3.3.7
 -  node-version: 16.15.1

**Comment by markstos** [comment]
There's no indication here that you searched for other webpack issues before submitting this. Please review the other webpack issues and summarize what you find here.

**Comment by markstos** [comment]
Funny, I got four thumbs down votes on my comment, but no one indicated that they searched for other webpack issues and summarized what they found. 

I'll summarize:  None of the maintainers use webpack, so if you want this improved, you'll need submit a PR including code, tests and anything that needs to be noted in the documentation.
