### ISSUE TITLE
Configs called local override the NODE_ENV variable

### ISSUE THREAD

**Issue by ekasprzyk** [node-config/node-config#685]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/node-config/node-config/wiki

### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
If I create a config with the name `local` my current config as specified in `NODE_ENV` will be ignored

### What is the expected behavior?
If I create a config with the name `local`, the current config I want to run will be used
OR
I search in Google for this special behaviour and I find clear documentation warning me that `local` is a reserved config that will override my current config

### Please tell us about your environment:

 -  node-config version: 3.3.7
 -  node-version: 18.x
 
### Other information

In various builds we have AWS environments which are named and a local/CI environment that runs in containers.
We previously had a `test` environment for local docker testing, but introduced the `test` AWS environment.  So I renamed the `test` config to `local`.
Cue three hours of headscratching.

**Comment by markstos** [comment]
This is not a bug, it's a long-standing documented behavior:

https://github.com/node-config/node-config/wiki/Configuration-Files#local-files

Yes, I realize "local" is popular for other uses, but `node-config` has behaved this way for 5+ years and this isn't something that we are considering changing now.

The only way a backwards compatible change could be safely made here would be to use some additional environment variable to trigger a different handling of "local" files, but in practice this comes up pretty rarely I'm not sure we want to add that complexity. 

If you have a proposal for a breaking-change feature request on how this might be implemented and are willing to implementing, open a new issue to discuss that.
