### ISSUE TITLE
Config breaks RegExp instances in v3.3.8

### ISSUE THREAD

**Issue by MartinKolarik** [node-config/node-config#693]
### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?

```js
// default.js
module.exports = { pattern: /x/ };

// app.js
config.get('pattern').test('')
```

In v3.3.8 this started to throw ` TypeError: Method RegExp.prototype.exec called on incompatible receiver [object RegExp]`
The issue is caused by proxy wrapping added in #516.

Setting `ALLOW_CONFIG_MUTATIONS=1` resolves the problem, and technically, calling regex methods may even result in modification of some of its internal properties, but it seems rather unfortunate overall to consider this a config mutation, especially when done in a patch release.

### What is the expected behavior?

Doesn't result in any errors, like in versions up to 3.3.7.

### Please tell us about your environment:

 -  node-config version: 3.3.8
 -  node-version: 16.17.0

**Comment by markstos** [comment]
This is a not a bug, it's a documented part of how JavaScript-type config files work. There's a `raw()` utility function for this.

https://github.com/node-config/node-config/wiki/Special-features-for-JavaScript-configuration-files#using-promises-processstdout-and-other-objects-in-javascript-config-files

**Comment by mikl** [comment]
This used to work, and it still does if you revert to 3.3.7.

Said documentation does not say anything about needing to use `raw()` on RegExps. And it’s not making the RegExp object _immutable_, its making it _useless_.

**Comment by MartinKolarik** [comment]
Thanks for the link @markstos, I have to say, I didn't come across the `raw()` helper in many years of using this module because it wasn't needed until `3.3.8`. Even if it was originally meant to work this way, it still seems this would be better enforced only in a new major version and not a patch release.

**Comment by markstos** [comment]
@MartinKolarik We strive for preserving backwards comparability. In this case, the `raw()` method was added and the document added about `raw()` 6 years ago, in 2016.   

Since the 3.3.8 release was working as it has been documented for many years, this wasn't considered a breaking change. 

I've run into problems like this myself during Mongoose upgrades-- We had accidentally used some unintentional behavior that quit working after upgrade, but Mongoose considered it a "bug fix", not a "breaking change.
