### ISSUE TITLE
config breaks `Date`s.

### ISSUE THREAD

**Issue by jwalton** [node-config/node-config#694]
### I'm submitting a ... 
  - bug report

### What is the current behavior?

config/default.js:

```js
module.exports = {
  options: {
    runDate: new Date(),
  },
};
```

index.js:

```js
const config = require('config');
const runDate = config.get('options.runDate');

console.log(runDate); // Prints the current date
console.log(runDate instanceof Date); // Prints true
runDate.getDate(); // Throws `TypeError: this is not a Date object.`
```

`runDate` is an instance of Date, and has the correct value, but calling most functions on the date object throw errors.  `runDate.getDate()` or `runDate.valueOf()` will result in a `TypeError: this is not a Date object.`.  Calling `.toString()` explicitly will throw the rather strange `TypeError: Method Date.prototype.toString called on incompatible receiver [object Date]`.

### What is the expected behavior?

Dates should be dates.

### Please tell us about your environment:

 -  node-config version: 3.3.8
 -  node-version: 16.17.0

**Comment by markstos** [comment]
This is not a bug, it's a documented part of how JavaScript-type config files work. There's a `raw()` utility function for this:

https://github.com/node-config/node-config/wiki/Special-features-for-JavaScript-configuration-files#using-promises-processstdout-and-other-objects-in-javascript-config-files
