### ISSUE TITLE
TypeScript: util.toObject does not load the specified config

### ISSUE THREAD

**Issue by Torr7s** [node-config/node-config#695]
### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
config/default.json:
```
{
  "app": {
    "port": 8080,
    "x": "",
    "y": "",
    "z": "",
    "firebase": {
      "type": "",
      "project_id": "",
      "private_key_id": "",
      "private_key": "",
      "client_email": "",
      "client_id": "",
      "auth_uri": "",
      "token_uri": "",
      "auth_provider_x509_cert_url": "",
      "client_x509_cert_url": ""
    }
  }
}
```

firebase/index.ts
```
import config, { IConfig } from 'config';

const firebaseConfig: IConfig = config.get('app.firebase');

console.log(firebaseConfig); /*only data from app.firebase, such as 'type', 'project_id', etc */

console.log(firebaseConfig.util.toObject()); /* all existing data in the config file, such as 'port', 'x', 'y', 'z' */
```
The util.toObject method returns all the settings from the configuration file, rather than just the configuration specified in its parameter. 

### What is the expected behavior?
Only return the specified configuration as an object.

### Please tell us about your environment:

 -  node-config version: ^3.3.8
 -  node-version: 16.17.0
 
###

**Comment by markstos** [comment]
This appears to be a TypeScript use issue. We have not documented that the syntax you are trying is expected to work. 

Try:

```
import config from require('config');
```

**Comment by Torr7s** [comment]
> This appears to be a TypeScript use issue. We have not documented that the syntax you are trying is expected to work.
> 
> Try:
> 
> ```
> import config from require('config');
> ```

That's not even a valid syntax.

**Comment by Torr7s** [comment]
> ### I'm submitting a ...
> * [x]  bug report
> * [  ] feature request
> * [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.
> 
> ### What is the current behavior?
> config/default.json:
> 
> ```
> {
>   "app": {
>     "port": 8080,
>     "x": "",
>     "y": "",
>     "z": "",
>     "firebase": {
>       "type": "",
>       "project_id": "",
>       "private_key_id": "",
>       "private_key": "",
>       "client_email": "",
>       "client_id": "",
>       "auth_uri": "",
>       "token_uri": "",
>       "auth_provider_x509_cert_url": "",
>       "client_x509_cert_url": ""
>     }
>   }
> }
> ```
> 
> firebase/index.ts
> 
> ```
> import config, { IConfig } from 'config';
> 
> const firebaseConfig: IConfig = config.get('app.firebase');
> 
> console.log(firebaseConfig); /*only data from app.firebase, such as 'type', 'project_id', etc */
> 
> console.log(firebaseConfig.util.toObject()); /* all existing data in the config file, such as 'port', 'x', 'y', 'z' */
> ```
> 
> The util.toObject method returns all the settings from the configuration file, rather than just the configuration specified in its parameter.
> 
> ### What is the expected behavior?
> Only return the specified configuration as an object.
> 
> ### Please tell us about your environment:
> * node-config version: ^3.3.8
> * node-version: 16.17.0

Just find out. I have to get the configuration with config.get and pass it to config.util.toObject, I cannot use the util.toObject from a fetched configuration, such as firebaseConfig.

```
import config, { IConfig } from 'config';

const firebaseConfig: IConfig = config.get('app.firebase');

console.log(config.util.toObject('app.firebase')); /* app.firebase*/
console.log(firebaseConfig.util.toObject()); /* Object containing the whole config */
console.log(config.util.toObject(firebaseConfig)); /* Object containing only what was expected */
```
