### ISSUE TITLE
Ability to set / update any variable for testing purpose. 

### ISSUE THREAD

**Issue by KunalBurangi** [node-config/node-config#702]
Use Case. 
Let's say I am setting an env variable for timeout it has a timeout of 10 minutes. 
now while testing I want the timeout for 30 sec. 
I can not update the env variable just for that test case, right? 

so we can make some feature for these kind of scenarios

**Comment by jantaylor** [comment]
You have a couple options. You could pull the initial timeout from config into a variable. Then update your variable through the tests
```js
let STATIC_TIMEOUT = Number(config.get('timeout'))

// In tests
STATIC_TIMEOUT = 30

// later tests
STATIC_TIMEOUT = 600
```

You could use Jest/Mocha mocks

You could convert your class/module that handles the timeout to take an input with a variable that changes and instantiate the new class with the changed timeouts OR allow updating the timeout with a method.

```js
// Initial class
const timeoutClass = new Timeout(Number(config.get('timeout')))

// new class with different timeout
const shortTimeoutClass = new Timeout(30)

// Or use a method
timeoutClass.updateTimeout(30)
```

**Comment by jantaylor** [comment]
I said all that, but then I found this wiki doc for you @KunalBurangi https://github.com/node-config/node-config/wiki/Altering-configuration-values-for-testing-at-runtime

```js
const mockRequire = require("mock-require");
const importFresh = require("import-fresh");

// set up config overrides so that calls to http services will fail fast
process.env.NODE_CONFIG = JSON.stringify({
  httpServices: {retryInterval: 1, retries: 1} 
});

const testConfig = importFresh("config");
expect(
  testConfig.get("httpServices.retryInterval"),
  "config value not set to 1"
).to.equal(1);
mockRequire("config", testConfig);

// set up and run tests 
```

**Comment by KunalBurangi** [comment]
@jantaylor - So basically the only option is to update the variable before you initialize the config right... 
no other option as the Config object is non-extensible so no test runner like moha or Sinon can stub it...

**Comment by markstos** [comment]
@KunalBurangi You previously asked the same question in  #651. Then I suggested you search previous issues the the related issues. Here you are asking the same question again with no hint that you've checked for previous issue discussion about this. 

Also, node-config has opened Github discussions as another way to get support.

`node-config` is immutable by design once the configuration is set. As @jantaylor pointed out, there are some solutions for the testing case.

**Comment by hacknlove** [comment]
```js
const config = require('config');

jest.mock('config', () => {
    const config = jest.requireActual('config');

    const configMock = {

    }

    return new Proxy(config, {
        get: (target, prop) => {
            if (prop === 'get') {
                return key => configMock.hasOwnProperty(key) ? configMock[key] : target[key];
            }

            if (prop === '__reset__') {
                return () => {
                    Object.keys(configMock).forEach(key => delete configMock[key]);
                }
            }

            return configMock[prop] ?? target[prop];
        },
        set: (target, prop, value) => {
            if (prop === 'get') {
                return false;
            }

            configMock[prop] = value;
            return true;
        }
    })
});


beforeEach(() => {
    config.__reset__();
});

it('allows to change the config for testing purposes', () => {
    config.foo = "bar";
    
    expect(config.foo).toBe("bar");
    
    config.foo = "buz";
    
    expect(config.foo).toBe("buz");
});
```
