### ISSUE TITLE
[BUG] [Docs] Documentation is silent on the 'load order' of NODE_CONFIG variable

### ISSUE THREAD

**Issue by peternann** [node-config/node-config#716]
The documentation does not clearly state the precedence of the JSON data which can be in the environment variable called NODE_CONFIG.

i.e. Is it supposed to over-ride file-based config like I assumed it would?

I am reading the doco for 3.3.9 at 27/Jan/2023.

The doco here says nothing about precedence:
https://github.com/node-config/node-config/wiki/Environment-Variables#node_config

And the doco here:
https://github.com/node-config/node-config/wiki/Configuration-Files#file-load-order
Does in fact mention "custom environment variables".

But the page and section here:
https://github.com/node-config/node-config/wiki/Environment-Variables#custom-environment-variables

Clearly shows that "NODE_CONFIG" is NOT what you call a "Custom Environment Variable".

So all in all, the doco makes no explicit statement (that I can find in obvious places), about the precedence / load order of NODE_CONFIG.

I would guess/imagine that it should come after all the files, but before the "Custom Environment Variables".

**Expected behavior**
I would expect an explicit, clear statement about where NODE_CONFIG falls in the load order, at both of the first 2 linked sections above.

P.S. I chose not to submit a doco PR, as I am not aware if the current behaviour is correct, or incorrect, as there is no explicit statement either way that I can find.

**Comment by peternann** [comment]
Thinking about this even more, this section:
https://github.com/node-config/node-config/wiki/Environment-Variables#node_config

Says:
"If NODE_CONFIG is supplied both from the OS environment and the command line, they'll both be used with command line values favored over OS environment values."

What means "supplied from the command line"???

OK, I found my way to this page:
https://github.com/node-config/node-config/wiki/Command-Line-Overrides

... There is something very wrong with these 2 sections...

That link just above is written as though doing "NODE_CONFIG=xyz node myapp.js" is using a "command line parameter" related to myapp.js. This is a gross misunderstanding of what is going on (At least in a Unix shell).

In a Unix shell the format "VAR=value node myapp.js" is precisely setting an 'environment variable', but only for the "node" process being started.

There is no way "they'll both be used" as described earlier since "VAR=value node ..." will override the environment variable completely at the start of the 'node' process.

These sections are plain wrong and need work!

**Comment by markstos** [comment]
The wiki is there for you to edit and improve. It seems like you've reviewed the code and docs and understand how it works now. Feel free to update the wiki docs to match the code.
