### ISSUE TITLE
[BUG] RegExp are proxified which breaks them

### ISSUE THREAD

**Issue by CGNonofr** [node-config/node-config#722]
**Describe the bug**
Due to [this commit](https://github.com/node-config/node-config/commit/405e4082b6b015329d4300911bd6998482953ee7), regexes are now broken.

If your configuration contains a regex, you'll get a proxified regex which seems to be ok but it will crash as soon as you try to use it with an error: `TypeError: RegExp.prototype.source getter called on non-RegExp object`

**Expected behavior**
You can put regexes in your config files (in cjs or ts format) and use it in your code

### Please tell us about your environment:

 -  node-config version: 3.3.9
 -  node-version: 16.19.1
 
### Other information

A workaround is to enable `ALLOW_CONFIG_MUTATIONS` but it's not an acceptable solution

**Comment by jeremy-daley-kr** [comment]
I'm getting the same error when either `String(obj)` or `obj.toString()`. Would love to know the progress on the PR that fixes this.

**Comment by markstos** [comment]
See https://github.com/node-config/node-config/issues/693 and the description of the raw() method.

**Comment by jeremy-daley-kr** [comment]
Hmm. I'd have to disagree in that issue's comment about not being a breaking change, but I digress. Does that mean you intend on closing this issue as well?

**Comment by markstos** [comment]
Closed by #775
