### ISSUE TITLE
[BUG] Documentation is missing

### ISSUE THREAD

**Issue by bukowskiadam** [node-config/node-config#735]
**Describe the bug**

Your wiki page is missing pages: https://github.com/node-config/node-config/wiki

**Expected behavior**

Wiki should work

**Screenshots**

Someone destroyed your wiki pages. This is visible when I clone wiki repo

![image](https://github.com/node-config/node-config/assets/1633333/5f28000d-be7c-4988-8a16-231726fd93c7)

It is not visible in the wiki history page: https://github.com/node-config/node-config/wiki/Home/_history

**Comment by allangomessl** [comment]
That smells really bad to me. 
<img width="568" alt="Screenshot 2023-05-16 at 17 48 37" src="https://github.com/node-config/node-config/assets/877723/d2785319-49f0-44d0-8e08-3a9241f84afb">

**Comment by lorenwest** [comment]
Wiki restored, thanks to the magic of git. If only all vandalism were so easy to restore...

**Comment by lorenwest** [comment]
Thank you for discovering this @bukowskiadam and @allangomessl
