### ISSUE TITLE
[BUG] Here's precisely how it doesn't work.

### ISSUE THREAD

**Issue by flaviotux** [node-config/node-config#760]
**First of all**
Thanks for your great work!

**Describe the bug**
I'm using YAML config within a docker optimized image installing non dev dependencies.
When I run the application I found the error `No YAML parser loaded.  Suggest adding js-yaml dependency to your package.json file.`

**Expected behavior**
As you can see it's important all the parsers to be as production dependencies.

**Screenshots**
<img width="681" alt="image" src="https://github.com/node-config/node-config/assets/49658066/78f50317-025d-452d-a034-7542ca2cc38b">
<img width="468" alt="image" src="https://github.com/node-config/node-config/assets/49658066/2f635b5d-3d5f-458a-90d6-9355fea46ae1">

### Please tell us about your environment:

 -  node-config version: 3.3.10
 -  node-version: 20.11.0

**Comment by markstos** [comment]
That’s correct and documented. A lot of users of this module, including me,
don’t use the YAML parser.

Install it as a dependency if you need it.

*Mark Stosberg* (he/him)

Director of Systems & Security

***@***.*** | 765.277.1916

https://www.rideamigos.com <https://rideamigos.com/>

Changing the way the world commutes.


<https://www.linkedin.com/company/rideamigos>
<https://www.twitter.com/rideamigos> <https://www.facebook.com/rideamigos>
<https://www.instagram.com/rideamigos>
<https://rideamigos.com/newsletter-sign-up/>

**Comment by markstos** [comment]
If we  installed all the parsers in production, that would only bloat the disk space and memory use in production. 

I run more than a hundred node apps on the same  server  in production which all use Node config. How many memory they use matters-- memory is one of the primary things I'm paying to rent. 

So, no, I won't want to pay for extra memory to keep the YAML parser in memory or on disk if I don't need it.

**Comment by markstos** [comment]
Yes, I  think we can all appreciate that CoffeeScript is an optional
dependency today, when  it was  a hotly requested parser at one point.

    Mark
